spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true